#! /bin/bash
clear
echo -e ""
echo -e "=============================-Menu-============================="
echo -e " * menu : รายการคำสั่งหลัก"
echo -e " "
echo -e " =========================-SSH, WebsocketSSH & OpenVPN-=============== ========== "
echo -e " * user-new  : สร้างบัญชี SSH & OpenVPN "
echo -e " * trial : สร้างบัญชีทดลองใช้ SSH & OpenVPN "
echo -e " * renew: ยืดอายุบัญชี SSH & OpenVPN ที่ใช้งานอยู่"
echo -e " * deleteuser : ลบบัญชี SSH & OpenVPN "
echo -e " * check : ตรวจสอบการเข้าสู่ระบบของผู้ใช้ SSH & OpenVPN "
echo -e " * member: Daftar สมาชิก SSH & OpenVPN "
echo -e " * delete : ลบผู้ใช้ที่หมดอายุ SSH & OpenVPN "
echo -e " * autokill : ตั้งค่า Autokill SSH "
echo -e " * checkuser : แสดงผู้ใช้ที่ทำ Multi Login SSH "
echo -e " * restart : เริ่มบริการใหม่ Dropbear, Squid3, OpenVPN และ SSH "
echo -e " "
echo -e " ===========================-Wireguard-================ ========= "
echo -e " * add-wg : สร้างบัญชี Wireguard "
echo -e " * del-wg : ลบบัญชี Wireguard "
echo -e " * renew-wg : ขยายอายุการใช้งานบัญชี Wireguard "
echo -e " "
echo -e " =============================-L2TP-=============== ============== "
echo -e " * add-l2tp : กำลังสร้างบัญชี L2TP "
echo -e " * del-l2tp : กำลังลบบัญชี L2TP "
echo -e " * renew-l2tp : ขยายอายุใช้งานบัญชี L2TP "
echo -e " "
echo -e " =============================-PPTP-=============== ============== "
echo -e " * add-pptp : สร้างบัญชี PPTP "
echo -e " * del-pptp : ลบบัญชี PPTP "
echo -e " * renew-pptp : ขยายอายุการใช้งานบัญชี PPTP "
echo -e " * check-pptp : ตรวจสอบการเข้าสู่ระบบของผู้ใช้ PPTP "
echo -e " "
echo -e " =============================-SSTP-=============== ============== "
echo -e " * add-sstp : สร้างบัญชี SSTP "
echo -e " * del-sstp : ลบบัญชี SSTP "
echo -e " * renew-sstp : ขยายอายุใช้งานบัญชี SSTP "
echo -e " * check-sstp : ตรวจสอบการเข้าสู่ระบบของผู้ใช้ SSTP "
echo -e " "
echo -e " =============================-SSR-============== =============== "
echo -e " * add-ssr : สร้างบัญชี SSR "
echo -e " * del-ssr : กำลังลบบัญชี SSR "
echo -e " * renew-ssr : ขยายอายุการใช้งานบัญชี SSR "
echo -e " "
echo -e " ========================-Shadowsocks OBFS-=================== === "
echo -e " * add-ss : การสร้างบัญชี Shadowsocks "
echo -e " * del-ss : ลบบัญชี Shadowsocks "
echo -e " * renew-ss : ขยายอายุบัญชี Shadowsocks ที่ใช้งานอยู่"
echo -e " * check-ss : ตรวจสอบการเข้าสู่ระบบของผู้ใช้ Shadowsocks "
echo -e " "
echo -e " =============================-VMESS-=============== ============= "
echo -e " * add-ws : สร้างบัญชี V2RAY Vmess Websocket "
echo -e " * del-ws : กำลังลบบัญชี V2RAY Vmess Websocket "
echo -e " * renew-ws : ขยายอายุใช้งานบัญชี Vmess "
echo -e " * check-ws : ตรวจสอบการเข้าสู่ระบบของผู้ใช้ V2RAY "
echo -e " * cert2vray : ต่ออายุใบรับรองบัญชี V2RAY "
echo -e " "
echo -e " =============================-VLESS-============== ============= "
echo -e " * add-vless : สร้างบัญชี V2RAY Vless Websocket "
echo -e " * del-vless : กำลังลบบัญชี V2RAY Vless Websocket "
echo -e " * renew-vless : ขยายอายุใช้งานบัญชี Vless "
echo -e " * check-ws : ตรวจสอบการเข้าสู่ระบบของผู้ใช้ V2RAY "
echo -e " "
echo -e " =============================-Trojan-=============== ============ "
echo -e " * add-tr : สร้างบัญชีโทรจัน"
echo -e " * del-tr : การลบบัญชีโทรจัน"
echo -e " * renew-tr : ขยายอายุการใช้งานบัญชีโทรจัน"
echo -e " * check-tr : ตรวจสอบ User Login Trojan "
echo -e " "
echo -e " =============================-ระบบ-=============== ============ "
echo -e " * add-host : เพิ่มหรือเปลี่ยน Subdomain Host สำหรับ VPS "
echo -e " * change-port : Change Port of Some Service "
echo -e " * wbmn : เมนู Webmin "
echo -e " * kernel-updt : อัปเดตเป็นเคอร์เนลล่าสุด"
echo -e " * limit-speed  : จำกัด ความเร็วแบนด์วิดธ์เซิร์ฟเวอร์"
echo -e " * ram : ตรวจสอบการใช้งาน VPS Ram "
echo -e " * reboot: รีบูต VPS "
echo -e " * speedtest : Speedtest VPS "
echo -e " * update : อัปเดตเป็นเวอร์ชันสคริปต์ล่าสุด"
echo -e " * info : กำลังแสดงข้อมูลระบบ"
echo -e " * about : สคริปต์ข้อมูลติดตั้งอัตโนมัติ"
echo -e " * exit : ออกจาก VPS "
echo -e " "
echo -e " ============================================= ================= "
echo -e " "